"""
Telegram bot command handlers.
"""

from src.utils.logger import get_logger
from src.data.market_data import MarketData
from src.analysis.multi_timeframe import MultiTimeframeAnalysis
from src.analysis.signal_confidence import SignalConfidence

logger = get_logger(__name__)


OTC_PAIRS = [
    "USDINR-OTC",
    "USDIDR-OTC",
    "USDPHP-OTC",
    "EURUSD-OTC",
    "GBPUSD-OTC",
    "USDJPY-OTC",
    "AUDUSD-OTC",
    "NZDUSD-OTC",
    "USDCAD-OTC",
    "USDCHF-OTC"
]


class CommandHandlers:
    """
    Telegram command handlers.
    """

    def __init__(self, market_data: MarketData):
        self.market_data = market_data
        self.mta = MultiTimeframeAnalysis(market_data)


    def get_otc_pairs(self):
        """
        Return OTC pair list for Telegram buttons.
        """
        return OTC_PAIRS


    async def handle_analyze(self, symbol: str) -> str:
        """
        Handle analysis after user selects OTC pair.
        """

        try:
            analysis = self.mta.analyze(symbol)

            confidence = SignalConfidence.calculate_confidence(
                analysis
            )

            message = self._format_analysis_message(
                symbol,
                analysis,
                confidence
            )

            return message

        except Exception as e:
            logger.error(
                f"Analysis error: {e}"
            )

            return (
                f"❌ Error analyzing {symbol}: {str(e)}"
            )


    async def handle_help(self) -> str:

        return """
📊 **OTC Signal Bot**

Commands:

/analyze - Select OTC pair
/status - Bot status
/help - Help

Supported OTC:
• USDINR-OTC
• USDIDR-OTC
• USDPHP-OTC
• EURUSD-OTC
• GBPUSD-OTC

Timeframes:
• 15m Trend
• 5m Setup
• 1m Confirmation
"""


    async def handle_status(self) -> str:

        try:

            symbols = self.market_data.get_symbols()

            return f"""
✅ **Bot Status: Online**

📈 OTC Pairs: {len(symbols)}
📊 Analysis Module: Ready
"""

        except Exception as e:

            logger.error(
                f"Status error: {e}"
            )

            return "❌ Error retrieving status"



    def _format_analysis_message(
        self,
        symbol: str,
        analysis: dict,
        confidence: dict
    ) -> str:

        trend_analysis = analysis.get(
            "trend",
            {}
        )

        setup_analysis = analysis.get(
            "setup",
            {}
        )

        confirmation_analysis = analysis.get(
            "confirmation",
            {}
        )


        overall_conf = confidence.get(
            "overall_confidence",
            0
        )


        if overall_conf >= 70:
            signal = "🟢 CALL"
        elif overall_conf >= 50:
            signal = "🟡 WAIT"
        else:
            signal = "🔴 PUT"


        return f"""
{signal}

📈 **Pair:** {symbol}

🎯 **Confidence:** {overall_conf}%

15m Trend:
{trend_analysis.get('trend','N/A')}

5m Setup:
{setup_analysis.get('trend','N/A')}

1m Confirmation:
{confirmation_analysis.get('trend','N/A')}

Generated by OTC Signal Bot
"""